/*
1. Create a variable name accountBalance and assign 1000 to that variable
2. Lets assume you spent $1 at the park when you went our for walk
3. Post Decrement a dollar from you accountBalance
4. Construct a string which should display below text

I spent a dollar to buy a water and not my new balance is N

1. Create a variable name age and assign your age to that variable
2. Lets assume today is your birthday 
3. Post Increment your age
4. Construct a string which should display below text

Since today is my birthday, I am N years of old
*/

let accountBalance = 1000
accountBalance--
console.log(`I spent a dollar to buy water and now my new balance is ${accountBalance}.`)

let myAge = 50
myAge++
console.log(`Since today is my birthday, I am ${myAge} years of old.`)


let var1=20
let varres1 = var1++ - (var1)

console.log(`varres1 = ${varres1}`)
console.log(`var1 = ${var1}`)